import type { PocBuildResult, PocFile } from "./pocService";

export interface PublishPocToGitHubInput {
  token: string;
  repoName: string;
  owner?: string;
  isPrivate?: boolean;
  description?: string;
  poc: PocBuildResult & { idea?: string; techStack?: string[]; aiStudioLink?: string };
}

export interface PublishPocToGitHubResult {
  owner: string;
  repo: string;
  url: string;
  defaultBranch: string;
  committedFiles: number;
}

export interface PublishPocAsPrInput {
  token: string;
  owner: string;
  repo: string;
  branchName?: string;
  baseBranch?: string;
  prTitle?: string;
  prBody?: string;
  commitMessage?: string;
  poc: PublishPocToGitHubInput["poc"];
}

export interface PublishPocAsPrResult {
  owner: string;
  repo: string;
  baseBranch: string;
  branch: string;
  prUrl: string;
  prNumber: number;
  prTitle: string;
  committedFiles: number;
}

interface GitHubUser {
  login: string;
}

interface GitHubRepo {
  html_url?: string;
  clone_url?: string;
  default_branch?: string;
}

const GH_API = "https://api.github.com";

function slugifyName(input: string): string {
  return input
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80) || "mirror-mind-poc";
}

function normalizeRepoName(value: string): string {
  const out = slugifyName(String(value ?? "").trim());
  if (!out) throw new Error("repoName is required");
  return out;
}

function normalizePath(input: string): string {
  const p = String(input ?? "").trim().replace(/\\/g, "/").replace(/^\/+/, "");
  if (!p || p.includes("..")) throw new Error(`Invalid file path: ${input}`);
  return p;
}

function textToBase64(input: string): string {
  return Buffer.from(input, "utf8").toString("base64");
}

async function ghRequest<T>(path: string, token: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${GH_API}${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${token}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...(init?.headers ?? {}),
    },
  });

  if (!response.ok) {
    const text = await response.text();
    throw new Error(`GitHub API ${path} failed (${response.status}): ${text.slice(0, 250)}`);
  }

  if (response.status === 204) {
    return {} as T;
  }
  return (await response.json()) as T;
}

async function getAuthenticatedUser(token: string): Promise<GitHubUser> {
  return ghRequest<GitHubUser>("/user", token);
}

async function getRepo(owner: string, repo: string, token: string): Promise<GitHubRepo | null> {
  try {
    return await ghRequest<GitHubRepo>(`/repos/${owner}/${repo}`, token);
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    if (msg.includes("(404)")) return null;
    throw error;
  }
}

async function createRepo(
  owner: string,
  repo: string,
  token: string,
  authenticatedUser: string,
  isPrivate: boolean,
  description: string
): Promise<GitHubRepo> {
  const payload = { name: repo, private: isPrivate, description, auto_init: true };
  if (owner === authenticatedUser) {
    return ghRequest<GitHubRepo>("/user/repos", token, {
      method: "POST",
      body: JSON.stringify(payload),
    });
  }
  return ghRequest<GitHubRepo>(`/orgs/${owner}/repos`, token, {
    method: "POST",
    body: JSON.stringify(payload),
  });
}

function ensureReadme(files: PocFile[], poc: PublishPocToGitHubInput["poc"]): PocFile[] {
  const hasReadme = files.some((f) => f.path.toLowerCase() === "readme.md");
  if (hasReadme) return files;

  const techStack = Array.isArray(poc.techStack) ? poc.techStack.join(", ") : "";
  const aiStudioLink = String(poc.aiStudioLink ?? "").trim();
  const readme = [
    `# ${poc.title || "Mirror Mind POC"}`,
    "",
    poc.summary || "",
    "",
    techStack ? `## Tech Stack\n${techStack}\n` : "",
    aiStudioLink ? `## AI Studio\n${aiStudioLink}\n` : "",
    "Generated by Mirror Mind.",
  ]
    .filter(Boolean)
    .join("\n");

  return [{ path: "README.md", content: readme }, ...files];
}

function uniqueFiles(files: PocFile[]): PocFile[] {
  const seen = new Set<string>();
  const out: PocFile[] = [];
  for (const file of files) {
    const path = normalizePath(file.path);
    if (seen.has(path)) continue;
    seen.add(path);
    out.push({ path, content: String(file.content ?? "") });
    if (out.length >= 40) break;
  }
  return out;
}

async function upsertFile(
  owner: string,
  repo: string,
  branch: string,
  token: string,
  file: PocFile
): Promise<void> {
  const path = normalizePath(file.path);
  const apiPath = path.split("/").map((p) => encodeURIComponent(p)).join("/");
  let existingSha: string | undefined;
  try {
    const existing = await ghRequest<{ sha?: string }>(
      `/repos/${owner}/${repo}/contents/${apiPath}?ref=${encodeURIComponent(branch)}`,
      token
    );
    existingSha = existing.sha;
  } catch (error) {
    const msg = error instanceof Error ? error.message : String(error);
    if (!msg.includes("(404)")) throw error;
  }

  await ghRequest(
    `/repos/${owner}/${repo}/contents/${apiPath}`,
    token,
    {
      method: "PUT",
      body: JSON.stringify({
        message: `chore: add POC file ${path}`,
        content: textToBase64(file.content),
        branch,
        sha: existingSha,
      }),
    }
  );
}

async function createBranch(
  owner: string,
  repo: string,
  token: string,
  baseBranch: string,
  desiredBranch: string
): Promise<string> {
  const ref = await ghRequest<{ object: { sha: string } }>(
    `/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(baseBranch)}`,
    token
  );

  let branch = desiredBranch;
  const maxAttempts = 5;
  for (let attempt = 0; attempt < maxAttempts; attempt++) {
    try {
      await ghRequest(`/repos/${owner}/${repo}/git/refs`, token, {
        method: "POST",
        body: JSON.stringify({
          ref: `refs/heads/${branch}`,
          sha: ref.object.sha,
        }),
      });
      return branch;
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      if (!msg.includes("(422)")) throw error;
      branch = `${desiredBranch}-${attempt + 2}`;
    }
  }

  throw new Error("Failed to create a unique branch for POC PR");
}

async function createPullRequest(
  owner: string,
  repo: string,
  token: string,
  title: string,
  body: string,
  head: string,
  base: string
): Promise<{ number: number; html_url: string }> {
  return ghRequest<{ number: number; html_url: string }>(`/repos/${owner}/${repo}/pulls`, token, {
    method: "POST",
    body: JSON.stringify({
      title,
      body,
      head,
      base,
    }),
  });
}

export async function publishPocToGitHub(input: PublishPocToGitHubInput): Promise<PublishPocToGitHubResult> {
  const token = String(input.token ?? "").trim();
  if (!token) throw new Error("githubToken is required");

  const me = await getAuthenticatedUser(token);
  const owner = String(input.owner ?? "").trim() || me.login;
  const repo = normalizeRepoName(input.repoName);
  const isPrivate = Boolean(input.isPrivate);
  const description = String(input.description ?? `POC generated by Mirror Mind: ${input.poc.title ?? repo}`).trim();

  let repoData = await getRepo(owner, repo, token);
  if (!repoData) {
    repoData = await createRepo(owner, repo, token, me.login, isPrivate, description);
  }

  const branch = String(repoData.default_branch ?? "main").trim() || "main";
  const filesFromPoc = Array.isArray(input.poc.files) ? input.poc.files : [];
  const files = uniqueFiles(ensureReadme(filesFromPoc, input.poc));
  if (!files.length) throw new Error("No files in POC draft to publish");

  for (const file of files) {
    await upsertFile(owner, repo, branch, token, file);
  }

  const repoUrl = repoData.html_url ?? `https://github.com/${owner}/${repo}`;
  return {
    owner,
    repo,
    url: repoUrl,
    defaultBranch: branch,
    committedFiles: files.length,
  };
}

export async function publishPocAsPullRequest(input: PublishPocAsPrInput): Promise<PublishPocAsPrResult> {
  const token = String(input.token ?? "").trim();
  if (!token) throw new Error("githubToken is required");

  const owner = String(input.owner ?? "").trim();
  const repo = normalizeRepoName(input.repo);
  if (!owner || !repo) throw new Error("owner and repo are required");

  const repoData = await getRepo(owner, repo, token);
  if (!repoData) throw new Error(`Repository ${owner}/${repo} not found or inaccessible`);

  const baseBranch = String(input.baseBranch ?? repoData.default_branch ?? "main").trim() || "main";
  const files = uniqueFiles(ensureReadme(Array.isArray(input.poc.files) ? input.poc.files : [], input.poc));
  if (!files.length) throw new Error("No files in POC draft to publish");

  const branchSeed = slugifyName(input.branchName ?? `mirror-mind/${input.poc.title || "poc"}-${Date.now()}`);
  const branch = await createBranch(owner, repo, token, baseBranch, branchSeed);
  const commitMessage = String(input.commitMessage ?? `chore: add POC draft for ${input.poc.title || "Mirror Mind"}`).trim();

  for (const file of files) {
    const path = normalizePath(file.path);
    const apiPath = path.split("/").map((p) => encodeURIComponent(p)).join("/");
    let existingSha: string | undefined;
    try {
      const existing = await ghRequest<{ sha?: string }>(
        `/repos/${owner}/${repo}/contents/${apiPath}?ref=${encodeURIComponent(branch)}`,
        token
      );
      existingSha = existing.sha;
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      if (!msg.includes("(404)")) throw error;
    }

    await ghRequest(
      `/repos/${owner}/${repo}/contents/${apiPath}`,
      token,
      {
        method: "PUT",
        body: JSON.stringify({
          message: commitMessage,
          content: textToBase64(file.content),
          branch,
          sha: existingSha,
        }),
      }
    );
  }

  const prTitle = String(input.prTitle ?? `POC: ${input.poc.title || repo}`).trim() || `POC: ${repo}`;
  const prBody = String(
    input.prBody ??
      [
        input.poc.summary || "Generated by Mirror Mind.",
        "",
        input.poc.idea ? `Idea: ${input.poc.idea}` : "",
        Array.isArray(input.poc.techStack) && input.poc.techStack.length
          ? `Tech stack: ${input.poc.techStack.join(", ")}`
          : "",
      ]
        .filter(Boolean)
        .join("\n")
  ).trim();

  const pr = await createPullRequest(owner, repo, token, prTitle, prBody, branch, baseBranch);

  return {
    owner,
    repo,
    baseBranch,
    branch,
    prUrl: pr.html_url,
    prNumber: pr.number,
    prTitle,
    committedFiles: files.length,
  };
}
